const ProductMale = [
    {
        id: "FullShirt1",
        name: "Lava Styles",
        price: 400,
        img: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt1f2944.jpg'),
        description: "Lava Styles Casual Shirt for Men Regular Fit Long Soild Sleeve Shirt Suitable for Event, Formal Wear.",
        img1: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt5e6470.jpg'),
        clr1: "#5e6470",
        img2: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt8ac6d1.jpg'),
        clr2: "#8ac6d1",
        img3: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt1f2944.jpg'),
        clr3: "#1f2944",
        img4: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt531928.jpg'),
        clr4: "#531928",
        img5: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt96c4f6.jpg'),
        clr5: "#96c4f6",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "FullShirt2",
        name: "Dennis Lingo",
        price: 500,
        img: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirt2f3533.jpg'),
        description: "Dennis Lingo Men's Casual Shirt comfortable and breathable, perfect for casual outings or everyday wear",
        img1: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirt9ba58d.jpg'),
        clr1: "#9ba58d",
        img2: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirta06233.jpg'),
        clr2: "#a06233",
        img3: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirtcaa183.jpg'),
        clr3: "#caa183",
        img4: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirt2f3533.jpg'),
        clr4: "#2f3533",
        img5: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirtcceaec.jpg'),
        clr5: "#cceaec",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "FullShirt3",
        name: "Chikokko",
        price: 700,
        img: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt50575f.jpg'),
        description: "Chikokko Men's Round Neck Full Sleeves Regular Dry Fit Gym Sports T-Shirt",
        img1: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirtcfd0d4.jpg'),
        clr1: "#cfd0d4",
        img2: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt5274ca.jpg'),
        clr2: "#5274ca",
        img3: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt9c485c.jpg'),
        clr3: "#9c485c",
        img4: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt50575f.jpg'),
        clr4: "#50575f",
        img5: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt7eb5cc.jpg'),
        clr5: "#7eb5cc",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "FullShirt4",
        name: "Montero",
        price: 900,
        img: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtaccbd0.jpg'),
        description: "Montero Men Cotton Round Neck Solid Full Sleeve T-Shirt",
        img1: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtb5c7af.jpg'),
        clr1: "#b5c7af",
        img2: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtaccbd0.jpg'),
        clr2: "#accbd0",
        img3: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtdc90ae.jpg'),
        clr3: "#dc90ae",
        img4: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirte2c5e1.jpg'),
        clr4: "#e2c5e1",
        img5: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirte4aaa6.jpg'),
        clr5: "#e4aaa6",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "FullShirt5",
        name: "RodZen",
        price: 1000,
        img: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt7c95b4.jpg'),
        description: "RodZen Men's Cotton Half Sleeve Regular Fit Striped T-Shirt",
        img1: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt7c95b4.jpg'),
        clr1: "#7c95b4",
        img2: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt8aaf69.jpg'),
        clr2: "#8aaf69",
        img3: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirtd0b28c.jpg'),
        clr3: "#d0b28c",
        img4: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirtb1656f.jpg'),
        clr4: "#b1656f",
        img5: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt7e8274.jpg'),
        clr5: "#7e8274",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "HalfShirt1",
        name: "Brucewane Men",
        price: 750,
        img: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt1f4045.jpg'),
        description: "Brucewane Men's 100% Cotton Half Sleeve Shirt",
        img1: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt1f4045.jpg'),
        clr1: "#1f4045",
        img2: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt212747.jpg'),
        clr2: "#212747",
        img3: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt405e9c.jpg'),
        clr3: "#405e9c",
        img4: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirtdcac7b.jpg'),
        clr4: "#dcac7b",
        img5: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirtf9dd81.jpg'),
        clr5: "#f9dd81",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "HalfShirt2",
        name: "Chikan Men",
        price: 650,
        img: require ('../MenOutfits/ShirtMenHalf/Chikan/Shirt323637.jpg'),
        description: "Chikan Men's Cotton Textured Half Sleeves Shirt",
        img1: require('../MenOutfits/ShirtMenHalf/Chikan/Shirt323637.jpg'),
        clr1: "#323637",
        img2: require('../MenOutfits/ShirtMenHalf/Chikan/Shirt343345.jpg'), 
        clr2: "#343345",
        img3: require('../MenOutfits/ShirtMenHalf/Chikan/Shirt5d91a6.jpg'),
        clr3: "#5d91a6",
        img4: require('../MenOutfits/ShirtMenHalf/Chikan/Shirtae5648.jpg'),
        clr4: "#ae5648",
        img5: require('../MenOutfits/ShirtMenHalf/Chikan/Shirtbb965f.jpg'),
        clr5: "#bb965f",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "HalfShirt3",
        name: "Kuons Avenue",
        price: 850,
        img: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt543c4a.jpg'),
        description: "Kuons Avenue Men's Snow White Linen Blend Casual Shirt  Half Sleeves Shirt for Men",
        img1: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt543c4a.jpg'),
        clr1: "#543c4a",
        img2: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt553d5d.jpg'),
        clr2: "#553d5d",
        img3: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt8f3143.jpg'),
        clr3: "#8f3143",
        img4: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt9ac7c2.jpg'),
        clr4: "#9ac7c2",
        img5: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirtc1e0f4.jpg'),
        clr5: "#c1e0f4",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "HalfShirt4",
        name: "Sirius Style",
        price: 950,
        img: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt313a37.jpg'),
        description: "Sirius Style is a fashionable and modern take on the traditional men's shirt",
        img1: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt313a37.jpg'),
        clr1: "#313a37",
        img2: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt3e3c41.jpg'),
        clr2: "#3e3c41",
        img3: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt9db0ac.jpg'),
        clr3: "#9db0ac",
        img4: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt9f2c3b.jpg'),
        clr4: "#9f2c3b",
        img5: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirtddb68b.jpg'),
        clr5: "#ddb68b",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "HalfShirt5",
        name: "Thomas Scott",
        price: 1000,
        img: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirt262b3f.jpg'),
        description: "Thomas Scott half shirt Men is a stylish and contemporary men's shirt designed with a unique half-length silhouette.",
        img1: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirt262b3f.jpg'),
        clr1: "#262b3f",
        img2: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirt672931.jpg'),
        clr2: "#672931",
        img3: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirtc9e0f0.jpg'),
        clr3: "#c9e0f0",
        img4: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirtd3d2d7.jpg'),
        clr4: "#d3d2d7",
        img5: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirtdcdadd.jpg'),
        clr5: "#dcdadd",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id:"Jeans1",
        name: "Urbano Fashion",
        price: 900,
        img: require ('../MenOutfits/MenJeans/Urbano/jeans131627.jpg'),
        description: "Urbano Fashion Men's Regular Fit Stylish & Trendy Shaded Washed Carbon Grey Jeans",
        img1: require ('../MenOutfits/MenJeans/Urbano/jeans131627.jpg'),
        clr1: "#131627",
        img2: require ('../MenOutfits/MenJeans/Urbano/jeans2d4571.jpg'),
        clr2: "#2d4571",
        img3: require ('../MenOutfits/MenJeans/Urbano/jeans4b4c50.jpg'),
        clr3: "#4b4c50",
        img4: require ('../MenOutfits/MenJeans/Urbano/jeans8b8b89.jpg'),
        clr4: "#8b8b89",
        img5: require ('../MenOutfits/MenJeans/Urbano/jeans95c0e2.jpg'),
        clr5: "#95c0e2",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id:"Jeans2",
        name: "Symbol Men",
        price: 1000,
        img: require ('../MenOutfits/MenJeans/Symbol/jeans12233d.jpg'),
        description: "Symbol Men Cotton Rich Stretch Jeans with the inherent nature of Indigo dyed fabrics",
        img1:  require ('../MenOutfits/MenJeans/Symbol/jeans12233d.jpg'),
        clr1: "#12233d",
        img2:  require ('../MenOutfits/MenJeans/Symbol/jeans3c5786.jpg'),
        clr2: "#3c5786",
        img3:  require ('../MenOutfits/MenJeans/Symbol/jeansa29da3.jpg'),
        clr3: "#a29da3",
        img4:  require ('../MenOutfits/MenJeans/Symbol/jeansdddddd.jpg'),
        clr4: "#dddddd",
        img5:  require ('../MenOutfits/MenJeans/Symbol/jeanse3dbc6.jpg'),
        clr5: "e3dbc6",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id:"Jeans3",
        name: "Pepe Jeans",
        price: 900,
        img: require ('../MenOutfits/MenJeans/Pepe/jeans2b2d3c.jpg'),
        description: "Pepe Jeans Men's Regular Pajama with soft anti-roll, microfiber waistband with comfort stretch",
        img1: require ('../MenOutfits/MenJeans/Pepe/jeans2b2d3c.jpg'),
        clr1: "#2b2d3c",
        img2: require ('../MenOutfits/MenJeans/Pepe/jeans2d2e40.jpg'),
        clr2: "#2d2e40",
        img3: require ('../MenOutfits/MenJeans/Pepe/jeans373543.jpg'),
        clr3: "#373543",
        img4: require ('../MenOutfits/MenJeans/Pepe/jeans393939.jpg'),
        clr4: "#393939",
        img5: require ('../MenOutfits/MenJeans/Pepe/jeansc4c3c1.jpg'),
        clr5: "#c4c3c1",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id:"Jeans4",
        name: "Peter England",
        price: 1200,
        img: require ('../MenOutfits/MenJeans/PeterEngland/jeans1a1a26.jpg'),
        description: "Peter England Men's Jeans offer a blend of style and comfort, designed for a modern, fashionable look.",
        img1: require ('../MenOutfits/MenJeans/PeterEngland/jeans1a1a26.jpg'),
        clr1: "#1a1a26",
        img2: require ('../MenOutfits/MenJeans/PeterEngland/jeans535459.jpg'),
        clr2: "#535459",
        img3: require ('../MenOutfits/MenJeans/PeterEngland/jeans586d82.jpg'),
        clr3: "#586d82",
        img4: require ('../MenOutfits/MenJeans/PeterEngland/jeans6b8091.jpg'),
        clr4: "#6b8091",
        img5: require ('../MenOutfits/MenJeans/PeterEngland/jeans7e9ac1.jpg'),
        clr5: "#7e9ac1",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id:"Jeans5",
        name: "Allen Solly",
        price: 950,
        img: require ('../MenOutfits/MenJeans/AllenSolly/jeans1e293f.jpg'),
        description: "Allen Solly Men's jeans with a slim silhouette and standard length, perfect for casual or semi-formal occasions.",
        img1: require ('../MenOutfits/MenJeans/AllenSolly/jeans1e293f.jpg'),
        clr1: "#1e293f",
        img2: require ('../MenOutfits/MenJeans/AllenSolly/jeans272729.jpg'),
        clr2: "#272729",
        img3: require ('../MenOutfits/MenJeans/AllenSolly/jeans2c2a2a.jpg'),
        clr3: "#2c2a2a",
        img4: require ('../MenOutfits/MenJeans/AllenSolly/jeans2c3c56.jpg'),
        clr4: "#2c3c56",
        img5: require ('../MenOutfits/MenJeans/AllenSolly/jeans6f8cb4.jpg'),
        clr5: "#6f8cb4",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "pant1",
        name: "Adbucks",
        price: 850,
        img: require ('../MenOutfits/MenPant/Adbucks/pant2e446d.jpg'),
        description: "Adbucks Men's Regular Fit Army Print Cargo Style 3/4th Pants microfiber with comfort stretch",
        img1: require ('../MenOutfits/MenPant/Adbucks/pant2e446d.jpg'),
        clr1: "#2e446d",
        img2: require ('../MenOutfits/MenPant/Adbucks/pant303032.jpg'),
        clr2: "#303032",
        img3: require ('../MenOutfits/MenPant/Adbucks/pant343338.jpg'),
        clr3: "#343338",
        img4: require ('../MenOutfits/MenPant/Adbucks/pant5a82aa.jpg'),
        clr4: "#5a82aa",
        img5: require ('../MenOutfits/MenPant/Adbucks/pant726e6b.jpg'),
        clr5: "#726e6b",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "pant2",
        name: "Allocate",
        price: 1000,
        img: require ('../MenOutfits/MenPant/Allocate/pant191925.jpg'),
        description: "Allocate Cotton Knitted Regularfit Basic Three Fourth Capris for Men with Side Zip Pocket for Sports Swim Cycling & Nightwear.",
        img1: require ('../MenOutfits/MenPant/Allocate/pant191925.jpg'),
        clr1: "#191925",
        img2: require ('../MenOutfits/MenPant/Allocate/pant242329.jpg'),
        clr2: "#242329",
        img3: require ('../MenOutfits/MenPant/Allocate/pant424a6e.jpg'),
        clr3: "#424a6e",
        img4: require ('../MenOutfits/MenPant/Allocate/pant45434e.jpg'),
        clr4: "#45434e",
        img5: require ('../MenOutfits/MenPant/Allocate/pantdbdbe7.jpg'),
        clr5: "#dbdbe7",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "pant3",
        name: "Code Styles",
        price: 900,
        img: require ('../MenOutfits/MenPant/CodeStyles/pant25283b.jpg'),
        description: "CodeStyles Cotton Cargo Shorts Pants Casual Loose Regular Fit Three Quarter Capris",
        img1: require ('../MenOutfits/MenPant/CodeStyles/pant25283b.jpg'),
        clr1: "#25283b",
        img2: require ('../MenOutfits/MenPant/CodeStyles/pant292a2e.jpg'),
        clr2: "#292a2e",
        img3: require ('../MenOutfits/MenPant/CodeStyles/pant3e4138.jpg'),
        clr3: "#3e4138",
        img4: require ('../MenOutfits/MenPant/CodeStyles/pant413131.jpg'),
        clr4: "#413131",
        img5: require ('../MenOutfits/MenPant/CodeStyles/pant747565.jpg'),
        clr5: "#747565",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "pant4",
        name: "Van Heusen",
        price: 1200,
        img: require ('../MenOutfits/MenPant/VanHeusen/pant0063b8.jpg'),
        description: "Van Heusen Men Capri Shorts - 100% Combed Cotton - Drawstring Waist, Functional Pockets",
        img1: require ('../MenOutfits/MenPant/VanHeusen/pant0063b8.jpg'),
        clr1: "#0063b8",
        img2: require ('../MenOutfits/MenPant/VanHeusen/pant1b191e.jpg'),
        clr2: "#1b191e",
        img3: require ('../MenOutfits/MenPant/VanHeusen/pant1f1d2a.jpg'),
        clr3: "#1f1d2a",
        img4: require ('../MenOutfits/MenPant/VanHeusen/pant3e3b36.jpg'),
        clr4: "#3e3b36",
        img5: require ('../MenOutfits/MenPant/VanHeusen/pant8a8a94.jpg'),
        clr5: "#8a8a94",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
    {
        id: "pant5",
        name: "Zeffit",
        price: 950,
        img: require ('../MenOutfits/MenPant/Zeffit/pant212025.jpg'),
        description: "Zeffit Men's Cotton Printed Three Fourth Capri great for camping, traveling, outdoor, indoor and casual wear.",
        img1: require ('../MenOutfits/MenPant/Zeffit/pant212025.jpg'),
        clr1: "#212025",
        img2: require ('../MenOutfits/MenPant/Zeffit/pant273a5b.jpg'),
        clr2: "#273a5b",
        img3: require ('../MenOutfits/MenPant/Zeffit/pant583934.jpg'),
        clr3: "#583934",
        img4: require ('../MenOutfits/MenPant/Zeffit/panta4989c.jpg'),
        clr4: "#a4989c",
        img5: require ('../MenOutfits/MenPant/Zeffit/pantdbe0e6.jpg'),
        clr5: "#dbe0e6",
        size: ["S", "M", "L", "XL", "2XL", "3XL"],
    },
];
export default ProductMale;