const ProductMale = [
    {
        id: "FullShirt1",
        name: "Lava Styles",
        price: 400,
        img: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt1f2944.jpg'),
        description: "Lava Styles Casual Shirt for Men Regular Fit Long Soild Sleeve Shirt Suitable for Event, Formal Wear.",
        img1: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt5e6470.jpg'),
        clr1: "#5e6470",
        img2: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt8ac6d1.jpg'),
        clr2: "#8ac6d1",
        img3: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt1f2944.jpg'),
        clr3: "#1f2944",
        img4: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt531928.jpg'),
        clr4: "#531928",
        img5: require ('../MenOutfits/ShirtMenFull/LavaStyles/Shirt96c4f6.jpg'),
        clr5: "#96c4f6",
    },
    {
        id: "FullShirt2",
        name: "Dennis Lingo",
        price: 500,
        img: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirt2f3533.jpg'),
        description: "Dennis Lingo Men's Casual Shirt comfortable and breathable, perfect for casual outings or everyday wear",
        img1: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirt9ba58d.jpg'),
        clr1: "#9ba58d",
        img2: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirta06233.jpg'),
        clr2: "#a06233",
        img3: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirtcaa183.jpg'),
        clr3: "#caa183",
        img4: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirt2f3533.jpg'),
        clr4: "#2f3533",
        img5: require ('../MenOutfits/ShirtMenFull/DennisLingoMens/Shirtcceaec.jpg'),
        clr5: "#cceaec",
    },
    {
        id: "FullShirt3",
        name: "Chikokko",
        price: 700,
        img: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt50575f.jpg'),
        description: "Chikokko Men's Round Neck Full Sleeves Regular Dry Fit Gym Sports T-Shirt",
        img1: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirtcfd0d4.jpg'),
        clr1: "#cfd0d4",
        img2: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt5274ca.jpg'),
        clr2: "#5274ca",
        img3: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt9c485c.jpg'),
        clr3: "#9c485c",
        img4: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt50575f.jpg'),
        clr4: "#50575f",
        img5: require ('../MenOutfits/ShirtMenFull/ChikokkoMens/Shirt7eb5cc.jpg'),
        clr5: "#7eb5cc",
    },
    {
        id: "FullShirt4",
        name: "Montero",
        price: 900,
        img: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtaccbd0.jpg'),
        description: "Montero Men Cotton Round Neck Solid Full Sleeve T-Shirt",
        img1: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtb5c7af.jpg'),
        clr1: "#b5c7af",
        img2: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtaccbd0.jpg'),
        clr2: "#accbd0",
        img3: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirtdc90ae.jpg'),
        clr3: "#dc90ae",
        img4: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirte2c5e1.jpg'),
        clr4: "#e2c5e1",
        img5: require ('../MenOutfits/ShirtMenFull/MonteroMen/Shirte4aaa6.jpg'),
        clr5: "#e4aaa6",
    },
    {
        id: "FullShirt5",
        name: "RodZen",
        price: 1000,
        img: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt7c95b4.jpg'),
        description: "RodZen Men's Cotton Half Sleeve Regular Fit Striped T-Shirt",
        img1: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt7c95b4.jpg'),
        clr1: "#7c95b4",
        img2: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt8aaf69.jpg'),
        clr2: "#8aaf69",
        img3: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirtd0b28c.jpg'),
        clr3: "#d0b28c",
        img4: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirtb1656f.jpg'),
        clr4: "#b1656f",
        img5: require ('../MenOutfits/ShirtMenFull/RodZenMens/Shirt7e8274.jpg'),
        clr5: "#7e8274",
    },
    {
        id: "HalfShirt1",
        name: "Brucewane Men",
        price: 750,
        img: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt1f4045.jpg'),
        description: "Brucewane Men's 100% Cotton Half Sleeve Shirt",
        img1: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt1f4045.jpg'),
        clr1: "#1f4045",
        img2: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt212747.jpg'),
        clr2: "#212747",
        img3: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirt405e9c.jpg'),
        clr3: "#405e9c",
        img4: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirtdcac7b.jpg'),
        clr4: "#dcac7b",
        img5: require ('../MenOutfits/ShirtMenHalf/Brucewane/Shirtf9dd81.jpg'),
        clr5: "#f9dd81",
    },
    {
        id: "HalfShirt2",
        name: "Chikan Men",
        price: 650,
        img: require ('../MenOutfits/ShirtMenHalf/Chikan/Shirt323637.jpg'),
        description: "Chikan Men's Cotton Textured Half Sleeves Shirt",
        img1: require('../MenOutfits/ShirtMenHalf/Chikan/Shirt323637.jpg'),
        clr1: "#323637",
        img2: require('../MenOutfits/ShirtMenHalf/Chikan/Shirt343345.jpg'), 
        clr2: "#343345",
        img3: require('../MenOutfits/ShirtMenHalf/Chikan/Shirt5d91a6.jpg'),
        clr3: "#5d91a6",
        img4: require('../MenOutfits/ShirtMenHalf/Chikan/Shirtae5648.jpg'),
        clr4: "#ae5648",
        img5: require('../MenOutfits/ShirtMenHalf/Chikan/Shirtbb965f.jpg'),
        clr5: "#bb965f",
    },
    {
        id: "HalfShirt3",
        name: "Kuons Avenue",
        price: 850,
        img: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt543c4a.jpg'),
        description: "Kuons Avenue Men's Snow White Linen Blend Casual Shirt  Half Sleeves Shirt for Men",
        img1: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt543c4a.jpg'),
        clr1: "#543c4a",
        img2: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt553d5d.jpg'),
        clr2: "#553d5d",
        img3: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt8f3143.jpg'),
        clr3: "#8f3143",
        img4: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirt9ac7c2.jpg'),
        clr4: "#9ac7c2",
        img5: require ('../MenOutfits/ShirtMenHalf/Kuons Avenue/Shirtc1e0f4.jpg'),
        clr5: "#c1e0f4",
    },
    {
        id: "HalfShirt4",
        name: "Sirius Style",
        price: 950,
        img: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt313a37.jpg'),
        description: "Sirius Style is a fashionable and modern take on the traditional men's shirt",
        img1: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt313a37.jpg'),
        clr1: "#313a37",
        img2: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt3e3c41.jpg'),
        clr2: "#3e3c41",
        img3: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt9db0ac.jpg'),
        clr3: "#9db0ac",
        img4: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirt9f2c3b.jpg'),
        clr4: "#9f2c3b",
        img5: require ('../MenOutfits/ShirtMenHalf/Sirius Style/Shirtddb68b.jpg'),
        clr5: "#ddb68b",
    },
    {
        id: "HalfShirt5",
        name: "Thomas Scott",
        price: 1000,
        img: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirt262b3f.jpg'),
        description: "Thomas Scott half shirt Men is a stylish and contemporary men's shirt designed with a unique half-length silhouette.",
        img1: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirt262b3f.jpg'),
        clr1: "#262b3f",
        img2: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirt672931.jpg'),
        clr2: "#672931",
        img3: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirtc9e0f0.jpg'),
        clr3: "#c9e0f0",
        img4: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirtd3d2d7.jpg'),
        clr4: "#d3d2d7",
        img5: require ('../MenOutfits/ShirtMenHalf/Thomas Scott/Shirtdcdadd.jpg'),
        clr5: "#dcdadd",
    },
];
export default ProductMale;